In [67]:
import pandas as pd
import numpy as np

In [68]:
#Read all data and concatenate in a single DF

df1 = pd.read_csv ('S&P 500 2000-2004.csv')
df2 = pd.read_csv ('S&P 500 2004-2009.csv')
df3 = pd.read_csv ('S&P 500 2009-2014.csv')
df4 = pd.read_csv ('S&P 500 2014-2018.csv')
df5 = pd.read_csv ('S&P 500 2018-2023.csv')

pdList = [df1, df2, df3, df4, df5]

df = pd.concat(pdList)
df.reset_index(drop=True, inplace=True)
df

Date                           Symbol Guid         R1  \
0          1/3/2000  1586e716-a9a4-44de-a669-08adb1647127  49.699700   
1          1/3/2000  204fe856-da52-48f7-b9cb-2ecf13c2d490  85.915916   
2          1/3/2000  3cd814a4-acb0-40f0-ab7b-e13a3b7c2dab  83.633634   
3          1/3/2000  75bfff85-23e6-47f0-bcf6-59200f8f6e88   5.675676   
4          1/3/2000  781d229c-69ff-4143-b7e4-2c861b30e6ea  71.831832   
...             ...                                   ...        ...   
2714283  2023-03-10  f022a3d5-b26b-446b-a85a-e7f2a79ac010  41.555556   
2714284  2023-03-10  f2303fc5-8122-463b-b020-40c5e9f9052b  85.644444   
2714285  2023-03-10  f38ca9b5-4828-498e-98d2-c98f6e124b79  63.933333   
2714286  2023-03-10  f430e51e-faf7-45e1-9a44-8dd7fc867f86  50.644444   
2714287  2023-03-10  f486d92b-2897-431b-a0a0-b05cab1957e3  11.266667   

                R2         R3         R4         R5  
0        49.389389  50.155155  47.977978  29.655656  
1        82.462462  84.174174  85.682349  90.533534  
2        79.589590  78.638639  80.670671  78.742743  
3         6.586587   7.902903   8.758759   7.918919  
4        72.822823  58.298298  44.661328  16.112112  
...            ...        ...        ...        ...  
2714283  45.985185  51.703704  51.343210  39.224444  
2714284  88.318519  90.911111  90.800000  85.822963  
2714285  69.918519  65.374074  71.429630  84.885185  
2714286  62.155556  74.400000  78.274074  88.498519  
2714287  11.866667  14.103704  19.995062  19.231111  

[2714288 rows x 7 columns]

In [69]:
#convert data types, sort data and remove unused columns

df['Date'] = pd.to_datetime(df['Date'])

df=df.sort_values(['Symbol Guid','Date'],ascending = [True,True])
df.reset_index(drop=True, inplace=True)

df=df.drop(['R1','R2','R3','R4'],axis='columns')

df.R5.astype('float')

0          10.906874
1          10.972413
2          11.042524
3          11.105777
4          11.172077
             ...    
2714283    64.258519
2714284    64.385185
2714285    64.471852
2714286    64.596296
2714287    64.719259
Name: R5, Length: 2714288, dtype: float64

In [70]:
#convert dataframe into a numpy array

matx=np.array(df)
matx

array([[Timestamp('2015-10-19 00:00:00'),
        '080b998a-8625-4e84-a82f-2d124f6eb55d', 10.90687395],
       [Timestamp('2015-10-20 00:00:00'),
        '080b998a-8625-4e84-a82f-2d124f6eb55d', 10.97241274],
       [Timestamp('2015-10-21 00:00:00'),
        '080b998a-8625-4e84-a82f-2d124f6eb55d', 11.04252401],
       ...,
       [Timestamp('2022-06-07 00:00:00'),
        'f67c74dd-8605-45f2-91aa-293f1c77c825', 64.47185185],
       [Timestamp('2022-06-08 00:00:00'),
        'f67c74dd-8605-45f2-91aa-293f1c77c825', 64.5962963],
       [Timestamp('2022-06-09 00:00:00'),
        'f67c74dd-8605-45f2-91aa-293f1c77c825', 64.71925926]],
      dtype=object)

In [71]:
#create bins

col=[2]
for i in range(len(matx)):
    for j in col:
        if matx[i,j]<=10:
            matx[i,j]=1
        elif matx[i,j]<=20 and matx[i,j]>10:
            matx[i,j]=2    
        elif matx[i,j]<=30 and matx[i,j]>20:
            matx[i,j]=3
        elif matx[i,j]<=40 and matx[i,j]>30:
            matx[i,j]=4
        elif matx[i,j]<=50 and matx[i,j]>40:
            matx[i,j]=5
        elif matx[i,j]<=60 and matx[i,j]>50:
            matx[i,j]=6
        elif matx[i,j]<=70 and matx[i,j]>60:
            matx[i,j]=7
        elif matx[i,j]<=80 and matx[i,j]>70:
            matx[i,j]=8
        elif matx[i,j]<=90 and matx[i,j]>80:
            matx[i,j]=9
        elif matx[i,j]<=100 and matx[i,j]>90:
            matx[i,j]=10

print(matx)

[[Timestamp('2015-10-19 00:00:00') '080b998a-8625-4e84-a82f-2d124f6eb55d'
  2]
 [Timestamp('2015-10-20 00:00:00') '080b998a-8625-4e84-a82f-2d124f6eb55d'
  2]
 [Timestamp('2015-10-21 00:00:00') '080b998a-8625-4e84-a82f-2d124f6eb55d'
  2]
 ...
 [Timestamp('2022-06-07 00:00:00') 'f67c74dd-8605-45f2-91aa-293f1c77c825'
  7]
 [Timestamp('2022-06-08 00:00:00') 'f67c74dd-8605-45f2-91aa-293f1c77c825'
  7]
 [Timestamp('2022-06-09 00:00:00') 'f67c74dd-8605-45f2-91aa-293f1c77c825'
  7]]


In [72]:
#convert data form np array to dataframe

dd=pd.DataFrame(matx, columns=['Date','Symbol Guid','Bin'])
dd

Date                           Symbol Guid Bin
0       2015-10-19  080b998a-8625-4e84-a82f-2d124f6eb55d   2
1       2015-10-20  080b998a-8625-4e84-a82f-2d124f6eb55d   2
2       2015-10-21  080b998a-8625-4e84-a82f-2d124f6eb55d   2
3       2015-10-22  080b998a-8625-4e84-a82f-2d124f6eb55d   2
4       2015-10-23  080b998a-8625-4e84-a82f-2d124f6eb55d   2
...            ...                                   ...  ..
2714283 2022-06-03  f67c74dd-8605-45f2-91aa-293f1c77c825   7
2714284 2022-06-06  f67c74dd-8605-45f2-91aa-293f1c77c825   7
2714285 2022-06-07  f67c74dd-8605-45f2-91aa-293f1c77c825   7
2714286 2022-06-08  f67c74dd-8605-45f2-91aa-293f1c77c825   7
2714287 2022-06-09  f67c74dd-8605-45f2-91aa-293f1c77c825   7

[2714288 rows x 3 columns]

In [73]:
#remove data above bin 10 (benchmark has values above 100)

dd.reset_index(drop=True)
dd= dd[dd['Bin']<=10]

In [74]:
#convert data types, sort data and reset index (first column)

dd['Date'] = pd.to_datetime(dd['Date'])
dd=dd.sort_values(['Symbol Guid','Date'],ascending = [True,True])
dd.reset_index(drop=True, inplace=True)

In [75]:
#convert data into a numpy array

df=np.array(dd)
df

array([[Timestamp('2015-10-19 00:00:00'),
        '080b998a-8625-4e84-a82f-2d124f6eb55d', 2],
       [Timestamp('2015-10-20 00:00:00'),
        '080b998a-8625-4e84-a82f-2d124f6eb55d', 2],
       [Timestamp('2015-10-21 00:00:00'),
        '080b998a-8625-4e84-a82f-2d124f6eb55d', 2],
       ...,
       [Timestamp('2022-06-07 00:00:00'),
        'f67c74dd-8605-45f2-91aa-293f1c77c825', 7],
       [Timestamp('2022-06-08 00:00:00'),
        'f67c74dd-8605-45f2-91aa-293f1c77c825', 7],
       [Timestamp('2022-06-09 00:00:00'),
        'f67c74dd-8605-45f2-91aa-293f1c77c825', 7]], dtype=object)

In [76]:
#calculate days spent in each bin

j=1
k=0;

df_zeros=df.shape[0]
final_array=np.zeros(shape=(len(df),4),dtype=object)

for i in range(1,df_zeros):
    if (df[i-1,1]==df[i,1] and df[i-1,2]==df[i,2]):
        j=j+1
    else:
        final_array[k,0]=df[i-1,0]
        final_array[k,1]=df[i-1,1]
        final_array[k,2]=df[i-1,2]
        final_array[k,3]=j
        k=k+1
        j=1
print(final_array)

[[Timestamp('2016-05-30 00:00:00') '080b998a-8625-4e84-a82f-2d124f6eb55d'
  2 161]
 [Timestamp('2016-08-29 00:00:00') '080b998a-8625-4e84-a82f-2d124f6eb55d'
  3 65]
 [Timestamp('2016-11-07 00:00:00') '080b998a-8625-4e84-a82f-2d124f6eb55d'
  4 50]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [77]:
#remove zeros

final_data=final_array[~np.all(final_array == 0, axis=1)]
final_data

array([[Timestamp('2016-05-30 00:00:00'),
        '080b998a-8625-4e84-a82f-2d124f6eb55d', 2, 161],
       [Timestamp('2016-08-29 00:00:00'),
        '080b998a-8625-4e84-a82f-2d124f6eb55d', 3, 65],
       [Timestamp('2016-11-07 00:00:00'),
        '080b998a-8625-4e84-a82f-2d124f6eb55d', 4, 50],
       ...,
       [Timestamp('2021-01-14 00:00:00'),
        'f67c74dd-8605-45f2-91aa-293f1c77c825', 6, 112],
       [Timestamp('2021-12-16 00:00:00'),
        'f67c74dd-8605-45f2-91aa-293f1c77c825', 5, 240],
       [Timestamp('2022-03-24 00:00:00'),
        'f67c74dd-8605-45f2-91aa-293f1c77c825', 6, 70]], dtype=object)

In [78]:
#export data into CSV file
pd.DataFrame(final_data).to_csv('Final-data-with-bins-days-R5.csv',index=False,header=False)